services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile.app
    ports:
      - "8081:80"
    depends_on:
      - nginx

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/usr/share/nginx/html/images:ro